# Generated by Django 5.2.4 on 2025-07-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='es_elegible',
            field=models.BooleanField(default=False),
        ),
    ]
